[DCS-166] Spotlight tutorial
Woven-dojo/dojo-frontend-app-learner-portal pull request #72
Opened 2022-09-23 10:14 UTC by tetianabrzezinska

https://woven-dojo.atlassian.net/browse/DCS-166
## Preview

![Screenshot 2022-09-23 at 10 54 16](https://user-images.githubusercontent.com/110455841/191938334-9e4b9128-91ae-47bd-91cf-1447a5d3819a.png)

## Changes

This PR is about adding a “spotlight” tutorial

## PR checks

* [x] Did you add a preview image?
* [x] Have you included the task ID in the PR title? (Format: `[ABC-###] - PR title`)
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Does your submission pass them?
* [x] Have you lint your code locally prior to submission?
* [x] Have you added an explanation of what your changes do?

2022-09-26 07:38 UTC, bartosz-szczecinski-gft requested changes

2022-09-26 07:38 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +    if (cookies.get('firstLogin')) {
Can we clean this up a bit? I think just:
```
if (!cookies.get('firstLogin')) {
      cookies.set('firstLogin', 'true', {
        path: '/',
      });
      setIsOpen(true);  
}
```
would be enough.

Also:

- we might want to use a different name (e.g. `spotlightTutorialShown`).
- what is the lifetime of this cookie?
- with this approach, the user will be shown the tutorial again if they login from different browser; we should consider if we need a backend to track this to not annoy users (future improvement?)

If we're going with cookies it might be worth to change it to localStorage instead (no need to bring in new module because it has a sane API, stored for the lifetime, not sent to BE so saves transfer).

2022-09-26 07:38 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +    const filtredTutorialSteps = tutorialSteps.filter(isElementInDOM);
Some of the elements (e.g. the learning path, course catalog) are loaded after the hook will be called. How is the spotlight handling it?

Can you maybe record a short video and attach it to the story?

2022-09-26 07:38 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +          <p className="reactour-header-title">Toutorial step out {currentStep + 1} of {tutorialSteps.length}</p>
```suggestion
          <p className="reactour-header-title">Tutorial step {currentStep + 1} out of {tutorialSteps.length}</p>
```

2022-09-26 07:38 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/data/steps.jsx
> +  {
What happens if we need to add a step in between current 2 and 3 (adding favourite)? Will we need to change the `.step-2` to `.step-3` etc?

Maybe we can just use descriptive names (e.g. `selector: '.tour-kickoff-survey`) instead.

2022-09-26 07:38 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/styles/_Dashboard.scss
> +  &-start-btn{
Maybe we can just use `span` instead of `div`?

2022-09-26 07:38 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/utils/common.js
> +  const nodes = document.querySelectorAll(step.selector);
```suggestion
  return !!document.querySelector(step.selector);
```

2022-09-26 08:48 UTC, tetianabrzezinska commented on src/components/dashboard/Dashboard.jsx
> +    const filtredTutorialSteps = tutorialSteps.filter(isElementInDOM);
[screen-capture.webm](https://user-images.githubusercontent.com/110455841/192233790-561c078a-b4ea-4b38-9489-5df6864dd3bc.webm)

2022-09-26 08:55 UTC, tetianabrzezinska commented on src/components/dashboard/styles/_Dashboard.scss
> +  &-start-btn{
Checked. With span mask doesn't look good
span
![Screenshot 2022-09-26 at 10 55 20](https://user-images.githubusercontent.com/110455841/192235348-554dfbeb-6279-4644-8a47-ef2f52dce2eb.png)

div
![Screenshot 2022-09-26 at 10 54 29](https://user-images.githubusercontent.com/110455841/192235263-bb753385-7d41-45cd-9651-a3b74f5beab2.png)

2022-09-26 13:10 UTC, tetianabrzezinska commented on src/components/dashboard/Dashboard.jsx
> +    const filtredTutorialSteps = tutorialSteps.filter(isElementInDOM);
Looks better 
[screen-capture (2).webm](https://user-images.githubusercontent.com/110455841/192284912-75031763-ba52-46e8-be09-06ab950ee37a.webm)

2022-09-27 05:35 UTC, bartosz-szczecinski-gft commented
Looks like after the changes the blocks are stuck together:

![image](https://user-images.githubusercontent.com/90377295/192440798-dd122bfb-586d-4b8d-b9b4-8f590dd54381.png)

Also, does the library allow us to disable closing the tutorial when user clicks on the "shadow" part, to prevent users from accidentally closing the tutorial?

2022-09-27 07:48 UTC, tetianabrzezinska commented
> Also, does the library allow us to disable closing the tutorial when user clicks on the "shadow" part, to prevent users from accidentally closing the tutorial?

yes. it works like that now

2022-09-28 07:27 UTC, tetiana1506 commented
> Also, does the library allow us to disable closing the tutorial when user clicks on the "shadow" part, to prevent users from accidentally closing the tutorial?

Fixed. Added 
onClickMask={() => null}

2022-09-29 05:51 UTC, bartosz-szczecinski-wp commented on src/components/dashboard/Dashboard.jsx
> +      setTutorialSteps(filtredTutorialSteps);
Since you're calling `setTutorialSteps` inside an effect that is trigged when `tutorialSteps` change, this will create an infinite loop. Why do we need this local variable at all?

Can we do something like:

```
  useLayoutEffect(() => {
    setTimeout(() => {
      if (!localStorage.getItem("spotlightTutorialShown")) {
        const filtredTutorialSteps = basicSteps.filter(isElementInDOM);
        setSteps(filtredTutorialSteps);
        localStorage.setItem("spotlightTutorialShown", true);
        setIsOpen(true);
      }
    }, 500);
  }, [setIsOpen, setSteps]);
```
(Will need to change how you get the number of steps for the prompt, but you can access `steps` from the useTour() return as well).

2022-10-03 12:02 UTC, bartosz-szczecinski-wp approved these changes

2022-10-04 07:03 UTC, merged